package alice.util;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ProcReader {

    public static Map<String, SymbolInfo> readElf(String elf){
        try {
            Map<String, SymbolInfo> map = new HashMap<>();
            ProcessBuilder processBuilder = new ProcessBuilder("/bin/nm","-a",elf);
            Process process = processBuilder.start();
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    line = line.trim();
                    String[] tmp = line.split(" ");
                    if(tmp.length == 3){
                        SymbolInfo symbolInfo = new SymbolInfo(Long.parseLong(tmp[0], 16), tmp[1].charAt(0), tmp[2]);
                        map.put(tmp[2], symbolInfo);
                    } else if(tmp.length == 2){
                        SymbolInfo symbolInfo = new SymbolInfo(0, tmp[0].charAt(0), tmp[1]);
                        map.put(tmp[1], symbolInfo);
                    }
                }
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            return map;
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    //Generated by Gemini.
    public static class MemoryMapping {
        public String addressRangeStart;
        public String addressRangeEnd;
        public String permissions;
        public long offset;
        public String device;
        public long inode;
        public String pathname;

        @Override
        public String toString() {
            return "MemoryMapping{" +
                    "addressRange='" + addressRangeStart + "-" + addressRangeEnd + '\'' +
                    ", permissions='" + permissions + '\'' +
                    ", offset='" + Long.toHexString(offset) + '\'' +
                    ", device='" + device + '\'' +
                    ", inode='" + inode + '\'' +
                    ", pathname='" + pathname + '\'' +
                    '}';
        }
    }

    //Generated by Gemini.
    public static List<MemoryMapping> parseProcMaps(int pid) {
        List<MemoryMapping> mappings = new ArrayList<>();
        String filePath = "/proc/" + pid + "/maps";

        try (
                FileInputStream fis = new FileInputStream(filePath);
                InputStreamReader isr = new InputStreamReader(fis, StandardCharsets.UTF_8);
                BufferedReader br = new BufferedReader(isr)
        ) {
            String line;
            while ((line = br.readLine()) != null) {
                // Split the line by spaces or multiple spaces
                String[] parts = line.trim().split("\\s+");
                if (parts.length >= 5) {
                    MemoryMapping map = new MemoryMapping();
                    String[] tmp = parts[0].split("-");
                    map.addressRangeStart = tmp[0];
                    map.addressRangeEnd = tmp[1];
                    map.permissions = parts[1];
                    map.offset = Long.parseLong(parts[2],16);
                    map.device = parts[3];
                    map.inode = Long.parseLong(parts[4]);

                    // Pathname may have spaces and appears after the first 5 parts
                    if (parts.length > 5) {
                        StringBuilder builder = new StringBuilder();
                        for (int i = 5; i < parts.length; i++) {
                            builder.append(parts[i]).append(" ");
                        }
                        map.pathname = builder.toString().trim();
                    } else {
                        map.pathname = ""; // Anonymous mapping
                    }
                    mappings.add(map);
                }
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return mappings;
    }

    public static class SymbolInfo {
        public final long offset;
        public final char type;
        public final String name;
        public SymbolInfo(long offset, char type, String name) {
            this.offset = offset;
            this.type = type;
            this.name = name;
        }

        @Override
        public int hashCode() {
            return name.hashCode();
        }

        @Override
        public boolean equals(Object obj) {
            return obj instanceof SymbolInfo && name.equals(((SymbolInfo)obj).name);
        }

        @Override
        public String toString() {
            return (offset != 0 ? (Long.toHexString(offset) + " ") : "") + type + " " + name;
        }
    }
}
