package alice.util;

import alice.Platform;
import net.fornwall.jelf.ElfFile;
import net.fornwall.jelf.ElfSymbol;
import net.fornwall.jelf.ElfSymbolTableSection;

import javax.management.*;
import java.io.*;
import java.lang.management.ManagementFactory;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public final class ProcReader {

    private static final Map<String, Map<String, SymbolInfo>> cache = new HashMap<>();

    public static boolean isElf(String path) {
        try (InputStream is = Files.newInputStream(Paths.get(path))) {
            byte[] head = new byte[4];
            int ret = is.read(head);
            return ret == 4 && 0x7f == head[0] && 'E' == head[1] && 'L' == head[2] && 'F' == head[3];
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public static Map<String, SymbolInfo> readElf(String path) {
        if (cache.containsKey(path)) {
            return cache.get(path);
        }
        try {
            ElfFile elf = ElfFile.from(Files.newInputStream(Paths.get(path)));
            Map<String, SymbolInfo> map = new HashMap<>();
            ElfSymbolTableSection symbols = elf.getSymbolTableSection();
            iterateSymbols(map, symbols);
            symbols = elf.getDynamicSymbolTableSection();
            iterateSymbols(map, symbols);
            cache.put(path, map);
            return map;
        } catch (Throwable e) {
            System.err.println(path);
            throw new RuntimeException(e);
        }
    }

    private static void iterateSymbols(Map<String, SymbolInfo> map, ElfSymbolTableSection symbols) {
        if (symbols != null) {
            for (ElfSymbol symbol : symbols.symbols) {
                if (symbol.getName() != null && symbol.st_shndx != 0x0) {
                    map.put(symbol.getName(), new SymbolInfo(symbol.st_value, (char) symbol.getType(), symbol.getName()));
                }
            }
        }
    }

    //Generated by Gemini.
    public static class MemoryMapping {
        public String addressRangeStart;
        public String addressRangeEnd;
        public String permissions;
        public long offset;
        public String device;
        public long inode;
        public String pathname;

        @Override
        public String toString() {
            return "MemoryMapping{" + "addressRange='" + addressRangeStart + "-" + addressRangeEnd + '\'' + ", permissions='" + permissions + '\'' + ", offset='" + Long.toHexString(offset) + '\'' + ", device='" + device + '\'' + ", inode='" + inode + '\'' + ", pathname='" + pathname + '\'' + '}';
        }
    }

    private static Map<String, ArrayList<MemoryMapping>> parseProcMapsBSD() {
        Map<String, ArrayList<MemoryMapping>> mappings = new HashMap<>();
        try {
            int pid = ProcessUtil.getPID();
            Process process = new ProcessBuilder("procstat", "-v", String.valueOf(pid)).redirectErrorStream(true).start();
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream(), StandardCharsets.UTF_8))) {
                String line;
                reader.readLine();//Skip first line
                while ((line = reader.readLine()) != null) {
                    line = line.trim();
                    if (line.isEmpty()) {
                        continue;
                    }

                    String[] parts = line.split("\\s+");
                    if (parts.length < 10) {
                        continue;
                    }

                    MemoryMapping mapping = new MemoryMapping();
                    mapping.addressRangeStart = trimHexPrefix(parts[1]);
                    mapping.addressRangeEnd = trimHexPrefix(parts[2]);
                    mapping.permissions = parts[3];
                    mapping.offset = -1;
                    mapping.device = null;
                    mapping.inode = -1;
                    mapping.pathname = parts.length > 10 ? join(parts, 10) : "";

                    ArrayList<MemoryMapping> list = mappings.computeIfAbsent(mapping.pathname, k -> new ArrayList<>());
                    list.add(mapping);
                }
            }
            int exitCode = process.waitFor();
            if (exitCode != 0) {
                throw new IOException("procstat -v exited with code " + exitCode);
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        return mappings;
    }

    private static String trimHexPrefix(String value) {
        return value.startsWith("0x") || value.startsWith("0X") ? value.substring(2) : value;
    }

    private static String join(String[] parts, int start) {
        StringBuilder builder = new StringBuilder();
        for (int i = start; i < parts.length; i++) {
            if (i > start) {
                builder.append(' ');
            }
            builder.append(parts[i]);
        }
        return builder.toString();
    }

    private static Map<String, ArrayList<MemoryMapping>> parseProcMapsMXBean() {
        Map<String, ArrayList<MemoryMapping>> mappings = new HashMap<>();
        try {
            MBeanServer server = ManagementFactory.getPlatformMBeanServer();
            ObjectName name = new ObjectName("com.sun.management:type=DiagnosticCommand");
            String result = (String) server.invoke(name, "vmDynlibs", new Object[]{null}, new String[]{"[Ljava.lang.String;"});
            String[] lines = result.split("\n");
            int i = Platform.win32 ? 1 : 0;
            for (; i < lines.length; i++) {
                String line = lines[i];
                if (line.startsWith("Total number of mappings:")) {
                    continue;
                }
                MemoryMapping mapping = parseMapping(line);
                if (mapping != null) {
                    ArrayList<MemoryMapping> list = mappings.computeIfAbsent(mapping.pathname, k -> new ArrayList<>());
                    list.add(mapping);
                }
            }
            return mappings;
        } catch (InstanceNotFoundException | MBeanException | ReflectionException | MalformedObjectNameException e) {
            e.getCause().printStackTrace(System.err);
            return null;
        }
    }

    public static Map<String, ArrayList<MemoryMapping>> parseProcMaps() {
        if (Platform.bsd) {//Java can't parse virtual maps on bsd itself, so skip trying to parse it through MXBean.
            return parseProcMapsBSD();
        }
        Map<String, ArrayList<MemoryMapping>> ret = parseProcMapsMXBean();
        if (ret != null) {
            if (!ret.isEmpty()) {
                return ret;
            } else {
                System.err.println("MXBean returns empty result!");
            }
        }
        System.err.println("Failed to parse memory mappings through MXBean!");
        if (Platform.win32) {
            return parseProcMapsWin32(ProcessUtil.getPID());
        }
        return parseProcMaps(ProcessUtil.getPID());
    }

    private static MemoryMapping parseMapping(String line) {
        if (line.startsWith("Total number of mappings:")) {
            return null;
        }
        MemoryMapping map = new MemoryMapping();
        if (Platform.win32) {
            map.addressRangeStart = line.substring(2, line.indexOf(" - "));
            map.addressRangeEnd = line.substring(line.indexOf(" - ") + 5, line.indexOf("\t") - 1);
            map.pathname = line.substring(line.indexOf("\t") + 1);
            map.offset = -1;
            map.inode = -1;
            map.device = null;
            map.permissions = null;
        } else {
            String[] parts = line.trim().split("\\s+");
            if (parts.length >= 5) {
                String[] tmp = parts[0].split("-");
                map.addressRangeStart = tmp[0];
                map.addressRangeEnd = tmp[1];
                map.permissions = parts[1];
                map.offset = Long.parseLong(parts[2], 16);
                map.device = parts[3];
                map.inode = Long.parseLong(parts[4]);

                // Pathname may have spaces and appears after the first 5 parts
                if (parts.length > 5) {
                    StringBuilder builder = new StringBuilder();
                    for (int i = 5; i < parts.length; i++) {
                        builder.append(parts[i]).append(" ");
                    }
                    map.pathname = builder.toString().trim();
                } else {
                    map.pathname = ""; // Anonymous mapping
                }
                return map;
            }
            return null;
        }

        return map;
    }

    private static Map<String, ArrayList<MemoryMapping>> parseProcMapsWin32(int pid) {
        Map<String, ArrayList<MemoryMapping>> mappings = new HashMap<>();
        Path jcmd = FileUtil.search(FileUtil.JAVA_HOME, "jcmd.exe");
        assert jcmd != null;
        ProcessBuilder processBuilder = new ProcessBuilder(jcmd.toString(), String.valueOf(pid), "VM.dynlibs");
        Process process;
        try {
            process = processBuilder.start();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.startsWith("0x")) {
                    MemoryMapping map = parseMapping(line);
                    if (map != null) {
                        ArrayList<MemoryMapping> list = mappings.computeIfAbsent(map.pathname, k -> new ArrayList<>());
                        list.add(map);
                    }
                }
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return mappings;
    }

    //Generated by Gemini.
    private static Map<String, ArrayList<MemoryMapping>> parseProcMaps(int pid) {
        Map<String, ArrayList<MemoryMapping>> mappings = new HashMap<>();
        String filePath = "/proc/" + pid + "/maps";

        try (FileInputStream fis = new FileInputStream(filePath); InputStreamReader isr = new InputStreamReader(fis, StandardCharsets.UTF_8); BufferedReader br = new BufferedReader(isr)) {
            String line;
            while ((line = br.readLine()) != null) {
                MemoryMapping map = parseMapping(line);
                if (map != null) {
                    ArrayList<MemoryMapping> list = mappings.computeIfAbsent(map.pathname, k -> new ArrayList<>());
                    list.add(map);
                }
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return mappings;
    }

    public static class SymbolInfo {
        public final long offset;
        public final char type;
        public final String name;

        public SymbolInfo(long offset, char type, String name) {
            this.offset = offset;
            this.type = type;
            this.name = name;
        }

        @Override
        public int hashCode() {
            return name.hashCode();
        }

        @Override
        public boolean equals(Object obj) {
            return obj instanceof SymbolInfo && name.equals(((SymbolInfo) obj).name);
        }

        @Override
        public String toString() {
            return (offset != 0 ? (Long.toHexString(offset) + " ") : "") + type + " " + name;
        }
    }
}
