package alice._native.stdlib;

import alice.Platform;
import alice._native.InlineHook;
import alice.injector.Shellcode;
import alice.injector.SymbolLookup;
import alice.util.AddressUtil;
import alice.util.CString;
import alice.util.MemoryUtil;
import alice.util.Unsafe;

public class system {

    private static int holder() {
        //noinspection ResultOfMethodCallIgnored
        System.getenv().keySet();
        return System.lineSeparator().length();
    }

    private static final long code_base;

    static {
        for (int i = 0; i < 20000; i++) {
            holder();
        }
        byte[] payload = new byte[36];
        //Shellcode first generated by llvm and fixed by Gemini.
        payload[0] = (byte) 0x55;
        payload[1] = (byte) 0x48;
        payload[2] = (byte) 0x89;
        payload[3] = (byte) 0xe5;
        payload[4] = (byte) 0x48;
        payload[5] = (byte) 0x83;
        payload[6] = (byte) 0xe4;
        payload[7] = (byte) 0xf0;
        payload[8] = (byte) 0x48;
        payload[9] = (byte) 0x83;
        payload[10] = (byte) 0xec;
        payload[11] = (byte) 0x20;
        payload[12] = (byte) 0x48;
        payload[13] = Platform.win32 ? (byte) 0xb9 : (byte) 0xbf;
        //_Command here
        payload[22] = (byte) 0x48;
        payload[23] = (byte) 0xb8;
        //function
        payload[32] = (byte) 0xff;
        payload[33] = (byte) 0xd0;
        payload[34] = (byte) 0xc9;
        payload[35] = (byte) 0xc3;
        code_base = MemoryUtil.allocate(23);
        AddressUtil.println(code_base);
        assert code_base != 0;
        Unsafe.writeBytes(code_base, payload);
        Unsafe.putLong(code_base + 24, SymbolLookup.lookup("system"));
        long address = Shellcode.getCompiledEntry(system.class, "holder", "()I");
        boolean success = InlineHook.simpleHook(address, code_base);
        assert success;
    }

    public static synchronized int invoke(String cmd) {
        CString cstr = CString.create(cmd);
        Unsafe.putLong(code_base + 14, cstr.getAddress());
        Shellcode.dump(code_base, 36, System.out);
        int ret = holder();
        cstr.release();
        return ret;
    }
}
